export const PLATFORMS = {
  FACEBOOK: "Facebook",
  INSTAGRAM: "Instagram",
  TWITTER: "Twitter",
  LINKEDIN: "LinkedIn",
};
export const BUSINESS_UNITS = {
  ASM: "ASM",
  ASM_PLUS: "ASM+",
  ASM_PRO: "ASM Pro",
  KCL: "KCL",
};
export const COUNTRIES = {
  US: "United States",
  UK: "United Kingdom",
  CA: "Canada",
  AU: "Australia",
  DE: "Germany",
  FR: "France",
  ES: "Spain",
  IT: "Italy",
  JP: "Japan",
  IN: "India",
  BR: "Brazil",
  MX: "Mexico",
  ZA: "South Africa",
  NG: "Nigeria",
  KE: "Kenya",
  AE: "United Arab Emirates",
  SA: "Saudi Arabia",
  SG: "Singapore",
  HK: "Hong Kong",
  CN: "China",
  GLOBAL: "Global",
} as const;
